N=int(input())
for i in range(N):
    opcode=list(input().split())
    rd=bin(int(opcode[1]))
    rd=rd[2:].zfill(3)
    ra=bin(int(opcode[2]))
    ra=ra[2:].zfill(3)
    rb=c=int(opcode[3])
    rb=c=bin(int(opcode[3]))
    rb=rb[2:].zfill(3)
    c=c[2:].zfill(4)
    
    bicode=[]
    
    if(opcode[0]=="ADD"):
        bicode.append("000000")
    elif(opcode[0]=="ADDC"):
        bicode.append("000010")
    elif(opcode[0]=="SUB"):
        bicode.append("000100")
    elif(opcode[0]=="SUBC"):
        bicode.append("000110")
    elif(opcode[0]=="MOV"):
        bicode.append("001000")
    elif(opcode[0]=="MOVC"):
        bicode.append("001010")
    elif(opcode[0]=="AND"):
        bicode.append("001100")
    elif(opcode[0]=="ANDC"):
        bicode.append("001110")
    elif(opcode[0]=="OR"):
        bicode.append("010000")
    elif(opcode[0]=="ORC"):
        bicode.append("010010")
    elif(opcode[0]=="NOT"):
        bicode.append("010100")
    elif(opcode[0]=="MULT"):
        bicode.append("011000")
    elif(opcode[0]=="MULTC"):
        bicode.append("011010")
    elif(opcode[0]=="LSFTL"):
        bicode.append("011100")
    elif(opcode[0]=="LSFTLC"):
        bicode.append("011110")
    elif(opcode[0]=="LSFTR"):
        bicode.append("100000")
    elif(opcode[0]=="LSFTRC"):
        bicode.append("100010")
    elif(opcode[0]=="ASFTR"):
        bicode.append("100100")
    elif(opcode[0]=="ASFTRC"):
        bicode.append("100110")
    elif(opcode[0]=="RL"):
        bicode.append("101000")
    elif(opcode[0]=="RLC"):
        bicode.append("101010")
    elif(opcode[0]=="RR"):
        bicode.append("101100")
    elif(opcode[0]=="RRC"):
        bicode.append("101110")
    bicode.append(rd+ra)
    if(bicode[0][4]=='0'):
        bicode.append(rb+'0')
    else:
        bicode.append(c)
    print(''.join(bicode))
